var f;f||(f=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},f),ba=[],ca="./this.program",h=(a,b)=>{throw b;},da="object"==typeof window,l="function"==typeof importScripts,ea="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,q="",fa,u,v;
if(ea){var fs=require("fs"),ha=require("path");q=l?ha.dirname(q)+"/":__dirname+"/";fa=(a,b)=>{a=a.startsWith("file://")?new URL(a):ha.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};v=a=>{a=fa(a,!0);a.buffer||(a=new Uint8Array(a));return a};u=(a,b,c,d=!0)=>{a=a.startsWith("file://")?new URL(a):ha.normalize(a);fs.readFile(a,d?void 0:"utf8",(e,k)=>{e?c(e):b(d?k.buffer:k)})};!f.thisProgram&&1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));ba=process.argv.slice(2);"undefined"!=typeof module&&
(module.exports=f);process.on("uncaughtException",a=>{if(!("unwind"===a||a instanceof w||a.context instanceof w))throw a;});h=(a,b)=>{process.exitCode=a;throw b;};f.inspect=()=>"[Emscripten Module object]"}else if(da||l)l?q=self.location.href:"undefined"!=typeof document&&document.currentScript&&(q=document.currentScript.src),q=0!==q.indexOf("blob:")?q.substr(0,q.replace(/[?#].*/,"").lastIndexOf("/")+1):"",fa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},l&&(v=
a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),u=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ia=f.print||console.log.bind(console),x=f.printErr||console.error.bind(console);Object.assign(f,aa);aa=null;f.arguments&&(ba=f.arguments);f.thisProgram&&(ca=f.thisProgram);f.quit&&(h=f.quit);
var y;f.wasmBinary&&(y=f.wasmBinary);var noExitRuntime=f.noExitRuntime||!0;"object"!=typeof WebAssembly&&ja("no native wasm support detected");var z,ka=!1,la,A,ma,na,B,C,oa,D;function pa(){var a=z.buffer;f.HEAP8=la=new Int8Array(a);f.HEAP16=ma=new Int16Array(a);f.HEAP32=B=new Int32Array(a);f.HEAPU8=A=new Uint8Array(a);f.HEAPU16=na=new Uint16Array(a);f.HEAPU32=C=new Uint32Array(a);f.HEAPF32=oa=new Float32Array(a);f.HEAPF64=D=new Float64Array(a)}var qa,ra=[],sa=[],ta=[],ua=[],va=[];
function wa(){var a=f.preRun.shift();ra.unshift(a)}var E=0,xa=null,F=null;function ja(a){if(f.onAbort)f.onAbort(a);a="Aborted("+a+")";x(a);ka=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function ya(a){return a.startsWith("data:application/octet-stream;base64,")}var G;G="doom.wasm";if(!ya(G)){var za=G;G=f.locateFile?f.locateFile(za,q):q+za}
function Aa(a){if(a==G&&y)return new Uint8Array(y);if(v)return v(a);throw"both async and sync fetching of the wasm failed";}function Ba(a){if(!y&&(da||l)){if("function"==typeof fetch&&!a.startsWith("file://"))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>Aa(a));if(u)return new Promise((b,c)=>{u(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>Aa(a))}
function Ca(a,b,c){return Ba(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{x("failed to asynchronously prepare wasm: "+d);ja(d)})}
function Da(a,b){var c=G;y||"function"!=typeof WebAssembly.instantiateStreaming||ya(c)||c.startsWith("file://")||ea||"function"!=typeof fetch?Ca(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){x("wasm streaming compile failed: "+e);x("falling back to ArrayBuffer instantiation");return Ca(c,a,b)}))}function w(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Ea=a=>{for(;0<a.length;)a.shift()(f)},Ha=a=>{var b=Fa();a();Ga(b)},Ia=0;function Ja(){for(var a=H.length-1;0<=a;--a)Ka(a);H=[];La=[]}var La=[];function Ma(){if(navigator.userActivation?navigator.userActivation.isActive:Ia&&Na.nc)for(var a=0;a<La.length;++a){var b=La[a];La.splice(a,1);--a;b.$c.apply(null,b.Oc)}}var H=[];function Ka(a){var b=H[a];b.target.removeEventListener(b.dc,b.Kc,b.ec);H.splice(a,1)}
function I(a){function b(d){++Ia;Na=a;Ma();a.hc(d);Ma();--Ia}if(!a.target)return-4;if(a.fc)a.Kc=b,a.target.addEventListener(a.dc,b,a.ec),H.push(a),Oa||(ua.push(Ja),Oa=!0);else for(var c=0;c<H.length;++c)H[c].target==a.target&&H[c].dc==a.dc&&Ka(c--);return 0}function Pa(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}
var Oa,Na,Qa,Ra,Sa,Ta,Ua,Va,Wa,Xa="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,J=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Xa)return Xa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var k=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|k);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|k<<6|g:(e&7)<<18|k<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
Ya=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0];function K(a){a=2<a?a?J(A,a):"":a;return Ya[a]||("undefined"!=typeof document?document.querySelector(a):void 0)}function Za(a){return 0>Ya.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
var $a=[],L=a=>{var b=$a[a];b||(a>=$a.length&&($a.length=a+1),$a[a]=b=qa.get(a));return b},M=(a,b,c)=>{var d=A;if(!(0<c))return 0;var e=b;c=b+c-1;for(var k=0;k<a.length;++k){var g=a.charCodeAt(k);if(55296<=g&&57343>=g){var m=a.charCodeAt(++k);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=
0;return b-e};function ab(a,b,c,d,e,k){Qa||(Qa=N(256));a={target:K(a),dc:k,fc:d,hc:function(g=event){var m=g.target.id?g.target.id:"",n=Qa;M(Pa(g.target),n+0,128);M(m,n+128,128);L(d)(e,n,b)&&g.preventDefault()},ec:c};return I(a)}
function bb(a,b,c,d,e,k){Ra||(Ra=N(176));a={target:K(a),nc:!0,dc:k,fc:d,hc:function(g){var m=Ra;D[m>>3]=g.timeStamp;var n=m>>2;B[n+2]=g.location;B[n+3]=g.ctrlKey;B[n+4]=g.shiftKey;B[n+5]=g.altKey;B[n+6]=g.metaKey;B[n+7]=g.repeat;B[n+8]=g.charCode;B[n+9]=g.keyCode;B[n+10]=g.which;M(g.key||"",m+44,32);M(g.code||"",m+76,32);M(g.char||"",m+108,32);M(g.locale||"",m+140,32);L(d)(e,m,b)&&g.preventDefault()},ec:c};return I(a)}
function cb(a,b,c){D[a>>3]=b.timeStamp;a>>=2;B[a+2]=b.screenX;B[a+3]=b.screenY;B[a+4]=b.clientX;B[a+5]=b.clientY;B[a+6]=b.ctrlKey;B[a+7]=b.shiftKey;B[a+8]=b.altKey;B[a+9]=b.metaKey;ma[2*a+20]=b.button;ma[2*a+21]=b.buttons;B[a+11]=b.movementX;B[a+12]=b.movementY;c=Za(c);B[a+13]=b.clientX-c.left;B[a+14]=b.clientY-c.top}
function O(a,b,c,d,e,k){Sa||(Sa=N(72));a=K(a);return I({target:a,nc:"mousemove"!=k&&"mouseenter"!=k&&"mouseleave"!=k,dc:k,fc:d,hc:function(g=event){cb(Sa,g,a);L(d)(e,Sa,b)&&g.preventDefault()},ec:c})}function db(a,b,c,d,e){Ta||(Ta=N(260));return I({target:a,dc:e,fc:d,hc:function(k=event){var g=Ta,m=document.pointerLockElement||document.kc||document.wc||document.uc;B[g>>2]=!!m;var n=m&&m.id?m.id:"";M(Pa(m),g+4,128);M(n,g+132,128);L(d)(20,g,b)&&k.preventDefault()},ec:c})}
function eb(a,b,c,d,e){return I({target:a,dc:e,fc:d,hc:function(k=event){L(d)(38,0,b)&&k.preventDefault()},ec:c})}
function fb(a,b,c,d){Ua||(Ua=N(36));a=K(a);return I({target:a,dc:"resize",fc:d,hc:function(e=event){if(e.target==a){var k=document.body;if(k){var g=Ua;B[g>>2]=e.detail;B[g+4>>2]=k.clientWidth;B[g+8>>2]=k.clientHeight;B[g+12>>2]=innerWidth;B[g+16>>2]=innerHeight;B[g+20>>2]=outerWidth;B[g+24>>2]=outerHeight;B[g+28>>2]=pageXOffset;B[g+32>>2]=pageYOffset;L(d)(10,g,b)&&e.preventDefault()}}},ec:c})}
function gb(a,b,c,d,e,k){Va||(Va=N(1696));a=K(a);return I({target:a,nc:"touchstart"==k||"touchend"==k,dc:k,fc:d,hc:function(g){for(var m,n={},p=g.touches,r=0;r<p.length;++r)m=p[r],m.yc=m.Ac=0,n[m.identifier]=m;for(r=0;r<g.changedTouches.length;++r)m=g.changedTouches[r],m.yc=1,n[m.identifier]=m;for(r=0;r<g.targetTouches.length;++r)n[g.targetTouches[r].identifier].Ac=1;p=Va;D[p>>3]=g.timeStamp;var t=p>>2;B[t+3]=g.ctrlKey;B[t+4]=g.shiftKey;B[t+5]=g.altKey;B[t+6]=g.metaKey;t+=7;var kb=Za(a),lb=0;for(r in n)if(m=
n[r],B[t]=m.identifier,B[t+1]=m.screenX,B[t+2]=m.screenY,B[t+3]=m.clientX,B[t+4]=m.clientY,B[t+5]=m.pageX,B[t+6]=m.pageY,B[t+7]=m.yc,B[t+8]=m.Ac,B[t+9]=m.clientX-kb.left,B[t+10]=m.clientY-kb.top,t+=13,31<++lb)break;B[p+8>>2]=lb;L(d)(e,p,b)&&g.preventDefault()},ec:c})}
function hb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,k){b.drawArraysInstancedANGLE(c,d,e,k)},a.drawElementsInstanced=function(c,d,e,k,g){b.drawElementsInstancedANGLE(c,d,e,k,g)})}
function ib(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function jb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
function mb(a){a.Qc=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")}function nb(a){a.Rc=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")}function ob(a){a.Tc=a.getExtension("WEBGL_multi_draw")}var pb=1,qb=[],P=[],rb=[],Q=[],R=[],S=[],sb=[],tb=[],T=[],ub={},vb=4;function U(a){wb||(wb=a)}function xb(a){for(var b=pb++,c=a.length;c<b;c++)a[c]=null;return b}
function yb(a,b){a.kc||(a.kc=a.getContext,a.getContext=function(d,e){e=a.kc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.zc?a.getContext("webgl2",b):a.getContext("webgl",b);return c?zb(c,b):0}function zb(a,b){var c=xb(tb),d={handle:c,attributes:b,version:b.zc,rc:a};a.canvas&&(a.canvas.Nc=d);tb[c]=d;("undefined"==typeof b.xc||b.xc)&&Ab(d);return c}
function Ab(a){a||(a=V);if(!a.Mc){a.Mc=!0;var b=a.rc;hb(b);ib(b);jb(b);mb(b);nb(b);2<=a.version&&(b.vc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.vc)b.vc=b.getExtension("EXT_disjoint_timer_query");ob(b);(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var wb,V;function Bb(a,b,c,d,e,k){a={target:K(a),dc:k,fc:d,hc:(g=event)=>{L(d)(e,0,b)&&g.preventDefault()},ec:c};I(a)}
function Cb(a,b,c,d){Wa||(Wa=N(104));return I({target:a,nc:!0,dc:"wheel",fc:d,hc:function(e=event){var k=Wa;cb(k,e,a);D[k+72>>3]=e.deltaX;D[k+80>>3]=e.deltaY;D[k+88>>3]=e.deltaZ;B[k+96>>2]=e.deltaMode;L(d)(9,k,b)&&e.preventDefault()},ec:c})}var Db=["default","low-power","high-performance"],Eb=a=>{if(!noExitRuntime){if(f.onExit)f.onExit(a);ka=!0}h(a,new w(a))},Fb=[null,[],[]],Gb=[];function W(a,b,c,d){for(var e=0;e<a;e++){var k=X[c](),g=k&&xb(d);k?(k.name=g,d[g]=k):U(1282);B[b+4*e>>2]=g}}
function Hb(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=X.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>V.version){U(1282);return}c=2*(X.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>V.version){U(1280);return}c=33307==a?3:0}if(void 0===c)switch(d=X.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":U(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:U(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)B[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){U(1280);x("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:U(1280);x("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}B[b>>2]=c}else U(1281)}
var Ib=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b};function Jb(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function Y(a){a-=5120;return 0==a?la:1==a?A:2==a?ma:4==a?B:6==a?oa:5==a||28922==a||28520==a||30779==a||30782==a?C:na}function Z(a){return 31-Math.clz32(a.BYTES_PER_ELEMENT)}
function Kb(a,b,c,d,e){a=Y(a);var k=Z(a),g=vb;return a.subarray(e>>k,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*(1<<k)+g-1&-g)>>k)}for(var Mb=a=>{var b=Ib(a)+1,c=Lb(b);M(a,c,b);return c},X,Nb=0;32>Nb;++Nb)Gb.push(Array(Nb));
var $b={j:()=>{ja("")},ea:function(){return"number"==typeof devicePixelRatio&&devicePixelRatio||1},fa:function(a,b,c){a=K(a);if(!a)return-4;a=Za(a);D[b>>3]=a.width;D[c>>3]=a.height;return 0},fb:(a,b,c)=>A.copyWithin(a,b,b+c),Za:function(a,b){function c(d){L(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},eb:a=>{var b=A.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=e.min.call(e,2147483648,
d+(65536-d%65536)%65536)-z.buffer.byteLength+65535>>>16;try{z.grow(e);pa();var k=1;break a}catch(g){}k=void 0}if(k)return!0}return!1},O:function(a,b,c,d){return ab(a,b,c,d,12,"blur")},da:function(a,b,c){a=K(a);if(!a)return-4;a.width=b;a.height=c;return 0},P:function(a,b,c,d){return ab(a,b,c,d,13,"focus")},Y:function(a,b,c,d){return bb(a,b,c,d,2,"keydown")},W:function(a,b,c,d){return bb(a,b,c,d,1,"keypress")},X:function(a,b,c,d){return bb(a,b,c,d,3,"keyup")},ca:function(a,b,c,d){return O(a,b,c,d,5,
"mousedown")},$:function(a,b,c,d){return O(a,b,c,d,33,"mouseenter")},_:function(a,b,c,d){return O(a,b,c,d,34,"mouseleave")},aa:function(a,b,c,d){return O(a,b,c,d,8,"mousemove")},ba:function(a,b,c,d){return O(a,b,c,d,6,"mouseup")},R:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.kc||document.body.wc||document.body.uc))return-1;a=K(a);if(!a)return-4;db(a,b,c,d,"mozpointerlockchange");db(a,b,c,d,"webkitpointerlockchange");db(a,b,c,d,"mspointerlockchange");
return db(a,b,c,d,"pointerlockchange")},Q:function(a,b,c,d){if(!document||!(document.body.requestPointerLock||document.body.kc||document.body.wc||document.body.uc))return-1;a=K(a);if(!a)return-4;eb(a,b,c,d,"mozpointerlockerror");eb(a,b,c,d,"webkitpointerlockerror");eb(a,b,c,d,"mspointerlockerror");return eb(a,b,c,d,"pointerlockerror")},_a:function(a,b,c,d){return fb(a,b,c,d)},S:function(a,b,c,d){return gb(a,b,c,d,25,"touchcancel")},T:function(a,b,c,d){return gb(a,b,c,d,23,"touchend")},U:function(a,
b,c,d){return gb(a,b,c,d,24,"touchmove")},V:function(a,b,c,d){return gb(a,b,c,d,22,"touchstart")},N:function(a,b,c,d){Bb(a,b,c,d,31,"webglcontextlost");return 0},M:function(a,b,c,d){Bb(a,b,c,d,32,"webglcontextrestored");return 0},Z:function(a,b,c,d){return(a=K(a))?"undefined"!=typeof a.onwheel?Cb(a,b,c,d):-1:-4},Xa:function(a,b){b>>=2;b={alpha:!!B[b],depth:!!B[b+1],stencil:!!B[b+2],antialias:!!B[b+3],premultipliedAlpha:!!B[b+4],preserveDrawingBuffer:!!B[b+5],powerPreference:Db[B[b+6]],failIfMajorPerformanceCaveat:!!B[b+
7],zc:B[b+8],Sc:B[b+9],xc:B[b+10],Lc:B[b+11],Uc:B[b+12],Vc:B[b+13]};a=K(a);return!a||b.Lc?0:yb(a,b)},Va:function(a,b){a=tb[a];b=b?J(A,b):"";b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&hb(X);"OES_vertex_array_object"==b&&ib(X);"WEBGL_draw_buffers"==b&&jb(X);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&mb(X);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&nb(X);"WEBGL_multi_draw"==b&&ob(X);return!!a.rc.getExtension(b)},Ya:function(a){a>>=2;for(var b=0;14>b;++b)B[a+
b]=0;B[a]=B[a+1]=B[a+3]=B[a+4]=B[a+8]=B[a+10]=1},Wa:function(a){V=tb[a];f.Pc=X=V&&V.rc;return!a||X?0:-5},Ib:Eb,hb:()=>52,db:function(){return 70},ib:(a,b,c,d)=>{for(var e=0,k=0;k<c;k++){var g=C[b>>2],m=C[b+4>>2];b+=8;for(var n=0;n<m;n++){var p=A[g+n],r=Fb[a];0===p||10===p?((1===a?ia:x)(J(r,0)),r.length=0):r.push(p)}e+=m}C[d>>2]=e;return 0},e:function(a){X.activeTexture(a)},B:function(a,b){X.attachShader(P[a],S[b])},b:function(a,b){35051==a?X.tc=b:35052==a&&(X.jc=b);X.bindBuffer(a,qb[b])},h:function(a,
b){X.bindFramebuffer(a,rb[b])},Ea:function(a,b){X.bindRenderbuffer(a,Q[b])},f:function(a,b){X.bindSampler(a,T[b])},a:function(a,b){X.bindTexture(a,R[b])},K:function(a){X.bindVertexArray(sb[a])},G:function(a,b,c,d){X.blendColor(a,b,c,d)},H:function(a,b){X.blendEquationSeparate(a,b)},I:function(a,b,c,d){X.blendFuncSeparate(a,b,c,d)},mb:function(a,b,c,d,e,k,g,m,n,p){X.blitFramebuffer(a,b,c,d,e,k,g,m,n,p)},Ga:function(a,b,c,d){2<=V.version?c&&b?X.bufferData(a,A,d,c,b):X.bufferData(a,b,d):X.bufferData(a,
c?A.subarray(c,c+b):b,d)},o:function(a,b,c,d){2<=V.version?c&&X.bufferSubData(a,b,A,d,c):X.bufferSubData(a,b,A.subarray(d,d+c))},oa:function(a){return X.checkFramebufferStatus(a)},xb:function(a,b,c,d){X.clearBufferfi(a,b,c,d)},la:function(a,b,c){X.clearBufferfv(a,b,oa,c>>2)},wb:function(a,b,c){X.clearBufferiv(a,b,B,c>>2)},l:function(a,b,c,d){X.colorMask(!!a,!!b,!!c,!!d)},Cb:function(a){X.compileShader(S[a])},Aa:function(a,b,c,d,e,k,g,m){2<=V.version?X.jc||!g?X.compressedTexImage2D(a,b,c,d,e,k,g,m):
X.compressedTexImage2D(a,b,c,d,e,k,A,m,g):X.compressedTexImage2D(a,b,c,d,e,k,m?A.subarray(m,m+g):null)},ya:function(a,b,c,d,e,k,g,m,n){X.jc?X.compressedTexImage3D(a,b,c,d,e,k,g,m,n):X.compressedTexImage3D(a,b,c,d,e,k,g,A,n,m)},va:function(){var a=xb(P),b=X.createProgram();b.name=a;b.qc=b.oc=b.pc=0;b.sc=1;P[a]=b;return a},Eb:function(a){var b=xb(S);S[b]=X.createShader(a);return b},D:function(a){X.cullFace(a)},Sa:function(a,b){for(var c=0;c<a;c++){var d=B[b+4*c>>2],e=qb[d];e&&(X.deleteBuffer(e),e.name=
0,qb[d]=null,d==X.tc&&(X.tc=0),d==X.jc&&(X.jc=0))}},m:function(a,b){for(var c=0;c<a;++c){var d=B[b+4*c>>2],e=rb[d];e&&(X.deleteFramebuffer(e),e.name=0,rb[d]=null)}},w:function(a){if(a){var b=P[a];b?(X.deleteProgram(b),b.name=0,P[a]=null):U(1281)}},Qa:function(a,b){for(var c=0;c<a;c++){var d=B[b+4*c>>2],e=Q[d];e&&(X.deleteRenderbuffer(e),e.name=0,Q[d]=null)}},L:function(a,b){for(var c=0;c<a;c++){var d=B[b+4*c>>2],e=T[d];e&&(X.deleteSampler(e),e.name=0,T[d]=null)}},A:function(a){if(a){var b=S[a];b?
(X.deleteShader(b),S[a]=null):U(1281)}},Ra:function(a,b){for(var c=0;c<a;c++){var d=B[b+4*c>>2],e=R[d];e&&(X.deleteTexture(e),e.name=0,R[d]=null)}},Oa:function(a,b){for(var c=0;c<a;c++){var d=B[b+4*c>>2];X.deleteVertexArray(sb[d]);sb[d]=null}},v:function(a){X.depthFunc(a)},u:function(a){X.depthMask(!!a)},d:function(a){X.disable(a)},J:function(a){X.disableVertexAttribArray(a)},ob:function(a,b,c){X.drawArrays(a,b,c)},pb:function(a,b,c,d){X.drawArraysInstanced(a,b,c,d)},na:function(a,b){for(var c=Gb[a],
d=0;d<a;d++)c[d]=B[b+4*d>>2];X.drawBuffers(c)},qb:function(a,b,c,d){X.drawElements(a,b,c,d)},sb:function(a,b,c,d,e){X.drawElementsInstanced(a,b,c,d,e)},i:function(a){X.enable(a)},tb:function(a){X.enableVertexAttribArray(a)},pa:function(a,b,c,d){X.framebufferRenderbuffer(a,b,c,Q[d])},k:function(a,b,c,d,e){X.framebufferTexture2D(a,b,c,R[d],e)},z:function(a,b,c,d,e){X.framebufferTextureLayer(a,b,R[c],d,e)},E:function(a){X.frontFace(a)},Ha:function(a,b){W(a,b,"createBuffer",qb)},qa:function(a,b){W(a,
b,"createFramebuffer",rb)},Fa:function(a,b){W(a,b,"createRenderbuffer",Q)},wa:function(a,b){W(a,b,"createSampler",T)},Ba:function(a,b){W(a,b,"createTexture",R)},Na:function(a,b){W(a,b,"createVertexArray",sb)},zb:function(a,b){return X.getAttribLocation(P[a],b?J(A,b):"")},c:function(a,b){Hb(a,b)},Fb:function(a,b,c,d){a=X.getProgramInfoLog(P[a]);null===a&&(a="(unknown error)");b=0<b&&d?M(a,d,b):0;c&&(B[c>>2]=b)},ta:function(a,b,c){if(c)if(a>=pb)U(1281);else if(a=P[a],35716==b)a=X.getProgramInfoLog(a),
null===a&&(a="(unknown error)"),B[c>>2]=a.length+1;else if(35719==b){if(!a.qc)for(b=0;b<X.getProgramParameter(a,35718);++b)a.qc=Math.max(a.qc,X.getActiveUniform(a,b).name.length+1);B[c>>2]=a.qc}else if(35722==b){if(!a.oc)for(b=0;b<X.getProgramParameter(a,35721);++b)a.oc=Math.max(a.oc,X.getActiveAttrib(a,b).name.length+1);B[c>>2]=a.oc}else if(35381==b){if(!a.pc)for(b=0;b<X.getProgramParameter(a,35382);++b)a.pc=Math.max(a.pc,X.getActiveUniformBlockName(a,b).length+1);B[c>>2]=a.pc}else B[c>>2]=X.getProgramParameter(a,
b);else U(1281)},Ab:function(a,b,c,d){a=X.getShaderInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?M(a,d,b):0;c&&(B[c>>2]=b)},ra:function(a,b,c){c?35716==b?(a=X.getShaderInfoLog(S[a]),null===a&&(a="(unknown error)"),B[c>>2]=a?a.length+1:0):35720==b?(a=X.getShaderSource(S[a]),B[c>>2]=a?a.length+1:0):B[c>>2]=X.getShaderParameter(S[a],b):U(1281)},Ta:function(a,b){if(2>V.version)return U(1282),0;var c=ub[a];if(c)return 0>b||b>=c.length?(U(1281),0):c[b];switch(a){case 7939:return c=X.getSupportedExtensions()||
[],c=c.concat(c.map(function(d){return"GL_"+d})),c=c.map(function(d){var e=Ib(d)+1,k=N(e);k&&M(d,k,e);return k}),c=ub[a]=c,0>b||b>=c.length?(U(1281),0):c[b];default:return U(1280),0}},s:function(a,b){b=b?J(A,b):"";if(a=P[a]){var c=a,d=c.mc,e=c.Ic,k;if(!d)for(c.mc=d={},c.Hc={},k=0;k<X.getProgramParameter(c,35718);++k){var g=X.getActiveUniform(c,k);var m=g.name;g=g.size;var n=Jb(m);n=0<n?m.slice(0,n):m;var p=c.sc;c.sc+=g;e[n]=[g,p];for(m=0;m<g;++m)d[p]=m,c.Hc[p++]=n}c=a.mc;d=0;e=b;k=Jb(b);0<k&&(d=parseInt(b.slice(k+
1))>>>0,e=b.slice(0,k));if((e=a.Ic[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||X.getUniformLocation(a,b)))return d}else U(1281);return-1},lb:function(a,b,c){for(var d=Gb[b],e=0;e<b;e++)d[e]=B[c+4*e>>2];X.invalidateFramebuffer(a,d)},Gb:function(a){a=P[a];X.linkProgram(a);a.mc=0;a.Ic={}},Ma:function(a,b){3317==a&&(vb=b);X.pixelStorei(a,b)},F:function(a,b){X.polygonOffset(a,b)},nb:function(a){X.readBuffer(a)},Da:function(a,b,c,d,e){X.renderbufferStorageMultisample(a,b,c,d,e)},C:function(a,b,c){X.samplerParameterf(T[a],
b,c)},g:function(a,b,c){X.samplerParameteri(T[a],b,c)},yb:function(a,b,c,d){X.scissor(a,b,c,d)},Db:function(a,b,c,d){for(var e="",k=0;k<b;++k){var g=d?B[d+4*k>>2]:-1,m=B[c+4*k>>2];g=m?J(A,m,0>g?void 0:g):"";e+=g}X.shaderSource(S[a],e)},Ka:function(a,b,c){X.stencilFunc(a,b,c)},ka:function(a,b,c,d){X.stencilFuncSeparate(a,b,c,d)},t:function(a){X.stencilMask(a)},Ja:function(a,b,c){X.stencilOp(a,b,c)},ja:function(a,b,c,d){X.stencilOpSeparate(a,b,c,d)},za:function(a,b,c,d,e,k,g,m,n){if(2<=V.version)if(X.jc)X.texImage2D(a,
b,c,d,e,k,g,m,n);else if(n){var p=Y(m);X.texImage2D(a,b,c,d,e,k,g,m,p,n>>Z(p))}else X.texImage2D(a,b,c,d,e,k,g,m,null);else X.texImage2D(a,b,c,d,e,k,g,m,n?Kb(m,g,d,e,n):null)},xa:function(a,b,c,d,e,k,g,m,n,p){if(X.jc)X.texImage3D(a,b,c,d,e,k,g,m,n,p);else if(p){var r=Y(n);X.texImage3D(a,b,c,d,e,k,g,m,n,r,p>>Z(r))}else X.texImage3D(a,b,c,d,e,k,g,m,n,null)},kb:function(a,b,c,d,e,k,g,m,n){if(2<=V.version)if(X.jc)X.texSubImage2D(a,b,c,d,e,k,g,m,n);else if(n){var p=Y(m);X.texSubImage2D(a,b,c,d,e,k,g,m,
p,n>>Z(p))}else X.texSubImage2D(a,b,c,d,e,k,g,m,null);else p=null,n&&(p=Kb(m,g,e,k,n)),X.texSubImage2D(a,b,c,d,e,k,g,m,p)},jb:function(a,b,c,d,e,k,g,m,n,p,r){if(X.jc)X.texSubImage3D(a,b,c,d,e,k,g,m,n,p,r);else if(r){var t=Y(p);X.texSubImage3D(a,b,c,d,e,k,g,m,n,p,t,r>>Z(t))}else X.texSubImage3D(a,b,c,d,e,k,g,m,n,p,null)},sa:function(a,b){var c=X,d=c.uniform1i;var e=X.Jc;if(e){var k=e.mc[a];"number"==typeof k&&(e.mc[a]=k=X.getUniformLocation(e,e.Hc[a]+(0<k?"["+k+"]":"")));a=k}else U(1282),a=void 0;
d.call(c,a,b)},n:function(a){a=P[a];X.useProgram(a);X.Jc=a},ub:function(a,b){X.vertexAttribDivisor(a,b)},vb:function(a,b,c,d,e,k){X.vertexAttribPointer(a,b,c,!!d,e,k)},ma:function(a,b,c,d){X.viewport(a,b,c,d)},Ua:function(){f.Bc=a=>{0!=Ob()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",f.Bc)},La:function(){f.Gc=a=>{const b=a.clipboardData.getData("text");Ha(()=>{const c=Mb(b);Pb(c)})};window.addEventListener("paste",f.Gc)},Ca:function(a){f.Xc=[];a=a?J(A,a):"";a=document.getElementById(a);
f.Cc=b=>{b.stopPropagation();b.preventDefault()};f.Dc=b=>{b.stopPropagation();b.preventDefault()};f.Ec=b=>{b.stopPropagation();b.preventDefault()};f.Fc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;f.Yc=c;Qb(c.length);for(let e=0;e<c.length;e++)Ha(()=>{const k=Mb(c[e].name);Rb(e,k)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);Sb(b.clientX,b.clientY,d)};a.addEventListener("dragenter",f.Cc,!1);a.addEventListener("dragleave",f.Dc,!1);a.addEventListener("dragover",
f.Ec,!1);a.addEventListener("drop",f.Fc,!1)},gb:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},r:function(){const a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){Tb()});document.body.append(a)},rb:function(){document.exitPointerLock&&document.exitPointerLock()},q:function(){document.getElementById("_sokol_app_input_element").focus()},Bb:function(a){a=a?
J(A,a):"";f.lc=document.getElementById(a);f.lc||console.log("sokol_app.h: invalid target:"+a);f.lc.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},Pa:function(){window.removeEventListener("beforeunload",f.Bc)},Ia:function(){window.removeEventListener("paste",f.Gc)},Hb:function(a){a=a?J(A,a):"";a=document.getElementById(a);a.removeEventListener("dragenter",f.Cc);a.removeEventListener("dragleave",f.Dc);a.removeEventListener("dragover",f.Ec);a.removeEventListener("drop",
f.Fc)},y:function(){f.lc&&f.lc.requestPointerLock&&f.lc.requestPointerLock()},cb:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),k=e.createImageData(a,b);k.data.set(A.subarray(c,c+a*b*4));e.putImageData(k,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},p:function(){document.getElementById("_sokol_app_input_element").blur()},$a:function(){return f.ic?f.ic.bufferSize:
0},bb:function(a,b,c){f.cc=null;f.ic=null;"undefined"!==typeof AudioContext?f.cc=new AudioContext({sampleRate:a,latencyHint:"interactive"}):(f.cc=null,console.log("sokol_audio.h: no WebAudio support"));return f.cc?(console.log("sokol_audio.h: sample rate ",f.cc.sampleRate),f.ic=f.cc.createScriptProcessor(c,0,b),f.ic.onaudioprocess=d=>{const e=d.outputBuffer.length,k=Ub(e);if(k){const g=d.outputBuffer.numberOfChannels;for(let m=0;m<g;m++){const n=d.outputBuffer.getChannelData(m);for(let p=0;p<e;p++)n[p]=
oa[(k>>2)+(g*p+m)]}}},f.ic.connect(f.cc.destination),a=()=>{f.cc&&"suspended"===f.cc.state&&f.cc.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},ab:function(){return f.cc?f.cc.sampleRate:0},ha:function(){const a=f.cc;null!==a&&(f.ic&&f.ic.disconnect(),a.close(),f.cc=null,f.ic=null)},x:function(a,b,c,d,e,k){b=b?J(A,b):"";const g=new XMLHttpRequest;g.open("GET",b);g.responseType="arraybuffer";
const m=0<d;m&&g.setRequestHeader("Range","bytes="+c+"-"+(c+d-1));g.onreadystatechange=function(){if(g.readyState==XMLHttpRequest.DONE)if(206==g.status||200==g.status&&!m){const n=new Uint8Array(g.response),p=n.length;p<=k?(A.set(n,e),Vb(a,d,p)):Wb(a)}else Xb(a,g.status)};g.send()},ia:function(a,b){b=b?J(A,b):"";const c=new XMLHttpRequest;c.open("HEAD",b);c.onreadystatechange=function(){if(c.readyState==XMLHttpRequest.DONE)if(200==c.status){const d=c.getResponseHeader("Content-Length");Yb(a,d)}else Xb(a,
c.status)};c.send()},ga:function(a,b){b=b?J(A,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}},ua:a=>{if(ea){if(!a)return 1;a=a?J(A,a):"";if(!a.length)return 0;a=require("child_process").Zc(a,[],{Wc:!0,stdio:"inherit"});var b=(c,d)=>c<<8|d;return null===a.status?b(0,(c=>{switch(c){case "SIGHUP":return 1;case "SIGQUIT":return 3;case "SIGFPE":return 8;case "SIGKILL":return 9;case "SIGALRM":return 14;case "SIGTERM":return 15}return 2})(a.signal)):
a.status<<8|0}if(!a)return 0;B[Zb()>>2]=52;return-1}};
(function(){function a(c){c=c.exports;f.asm=c;z=f.asm.Jb;pa();qa=f.asm._b;sa.unshift(f.asm.Kb);E--;f.monitorRunDependencies&&f.monitorRunDependencies(E);if(0==E&&(null!==xa&&(clearInterval(xa),xa=null),F)){var d=F;F=null;d()}return c}var b={a:$b};E++;f.monitorRunDependencies&&f.monitorRunDependencies(E);if(f.instantiateWasm)try{return f.instantiateWasm(b,a)}catch(c){return x("Module.instantiateWasm callback failed with error: "+c),!1}Da(b,function(c){a(c.instance)});return{}})();
function N(){return(N=f.asm.Lb).apply(null,arguments)}
var Tb=f.__sapp_emsc_notify_keyboard_hidden=function(){return(Tb=f.__sapp_emsc_notify_keyboard_hidden=f.asm.Mb).apply(null,arguments)},Pb=f.__sapp_emsc_onpaste=function(){return(Pb=f.__sapp_emsc_onpaste=f.asm.Nb).apply(null,arguments)},Ob=f.__sapp_html5_get_ask_leave_site=function(){return(Ob=f.__sapp_html5_get_ask_leave_site=f.asm.Ob).apply(null,arguments)},Qb=f.__sapp_emsc_begin_drop=function(){return(Qb=f.__sapp_emsc_begin_drop=f.asm.Pb).apply(null,arguments)},Rb=f.__sapp_emsc_drop=function(){return(Rb=
f.__sapp_emsc_drop=f.asm.Qb).apply(null,arguments)},Sb=f.__sapp_emsc_end_drop=function(){return(Sb=f.__sapp_emsc_end_drop=f.asm.Rb).apply(null,arguments)};f.__sapp_emsc_invoke_fetch_cb=function(){return(f.__sapp_emsc_invoke_fetch_cb=f.asm.Sb).apply(null,arguments)};
var ac=f._main=function(){return(ac=f._main=f.asm.Tb).apply(null,arguments)},Yb=f.__sfetch_emsc_head_response=function(){return(Yb=f.__sfetch_emsc_head_response=f.asm.Ub).apply(null,arguments)},Vb=f.__sfetch_emsc_get_response=function(){return(Vb=f.__sfetch_emsc_get_response=f.asm.Vb).apply(null,arguments)},Xb=f.__sfetch_emsc_failed_http_status=function(){return(Xb=f.__sfetch_emsc_failed_http_status=f.asm.Wb).apply(null,arguments)},Wb=f.__sfetch_emsc_failed_buffer_too_small=function(){return(Wb=f.__sfetch_emsc_failed_buffer_too_small=
f.asm.Xb).apply(null,arguments)},Ub=f.__saudio_emsc_pull=function(){return(Ub=f.__saudio_emsc_pull=f.asm.Yb).apply(null,arguments)};function Zb(){return(Zb=f.asm.Zb).apply(null,arguments)}function Fa(){return(Fa=f.asm.$b).apply(null,arguments)}function Ga(){return(Ga=f.asm.ac).apply(null,arguments)}function Lb(){return(Lb=f.asm.bc).apply(null,arguments)}f.___start_em_js=179620;f.___stop_em_js=189295;var bc;F=function cc(){bc||dc();bc||(F=cc)};
function ec(a=[]){var b=ac;a.unshift(ca);var c=a.length,d=Lb(4*(c+1)),e=d>>2;a.forEach(g=>{B[e++]=Mb(g)});B[e]=0;try{var k=b(c,d);Eb(k,!0)}catch(g){g instanceof w||"unwind"==g||h(1,g)}}
function dc(){var a=ba;function b(){if(!bc&&(bc=!0,f.calledRun=!0,!ka)){Ea(sa);Ea(ta);if(f.onRuntimeInitialized)f.onRuntimeInitialized();fc&&ec(a);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var c=f.postRun.shift();va.unshift(c)}Ea(va)}}if(!(0<E)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)wa();Ea(ra);0<E||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);b()},
1)):b())}}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var fc=!0;f.noInitialRun&&(fc=!1);dc();
