name: Build, Obfuscate, and Deploy

on:
  push:
    branches:
      - main  # Adjust if your main branch has a different name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Adjust to your required Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build the page
      run: npm run build  # Adjust if your build command is different

    - name: Obfuscate JavaScript
      run: |
        npm install -g javascript-obfuscator
        javascript-obfuscator build/ --output build/
      env:
        INPUT_DIR: build  # Adjust if your build directory is different

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build  # Adjust if your build directory is different
