name: Count Deployments

on:
  workflow_dispatch:

jobs:
  count-deployments:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get the number of deployments
        id: count_deployments
        run: |
          COUNT=$(gh deployment list --json environments --jq 'length')
          echo "::set-output name=deployment_count::$COUNT"

      - name: Output the number of deployments
        run: echo "The number of deployments is ${{ steps.count_deployments.outputs.deployment_count }}"
